language: java
jdk: openjdk11
services:
- docker
before_install:
- docker run -d --name rabbit -p 5672:5672 rabbitmq:3.6
- mkdir -p ~/.gradle
- echo "artifactory_user=${ARTIFACTORY_USERNAME}" >> ~/.gradle/gradle.properties
- echo "artifactory_password=${ARTIFACTORY_PASSWORD}" >> ~/.gradle/gradle.properties

install: true
script:
- |
  if [[ $TRAVIS_COMMIT_MESSAGE != 'SNAPSHOT UPDATE' ]]; then
      ./gradlew build  --info --refresh-dependencies ;
  fi
env:
  global:
  - SPRING_PROFILES_ACTIVE=default,integration-tests
branches:
  only:
  - master
after_success:
