server:
  port: 8030

spring:
  application:
    name: census-fwmt-outcome-service
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  security:
    user:
      name: "user"
      password: "password"
  datasource:
    url: jdbc:postgresql://localhost/postgres?currentSchema=fwmtg
    driver-class-name: org.postgresql.Driver
    schema: classpath:/schema.sql
    continue-on-error: false
    username: postgres
    password: postgres
    initialization-mode: always      

management:
  # Place /info and /health in the root
  endpoints.web.base-path: ''
  endpoint:
    health:
      show-details: always

rabbitmq:
  username: "guest"
  password: "guest"
  hostname: "localhost"
  port: 5672
  virtualHost: "/"
  initialInterval: 5000
  multiplier: 3.0
  maxInterval: 45000
  rmOutcomeExchange: "events"

logging:
  profile: DEV
  level:
    root: WARN
    uk.gov.ons.census.fwmt: INFO
    org.springframework.security: INFO
    org.springframework.web: INFO
    org.springframework.amqp: INFO
    org.hibernate: INFO
    org.apache.commons.dbcp2: INFO
    org.springframework: INFO

redis:
  host: "localhost"
  port: 6379
  password: "password"
  database: 1

outcomeservice:
  outcomeCodeLookup:
    path: classpath:/outcomeCodeLookup.txt
  reasonCodeLookup:
    path: classpath:/reasonCodeLookup.txt
    
    